### ISSUE TITLE
Bug in Estimated XP Progress

### ISSUE THREAD

**Issue by highpitch** [ClanTools/Tracker#1]
It shows I am 0 battles from the Obj 140. Which is true, but somewhat pointless to display. It also shows I am 65 from the Bat Chat, but I already have it researched. 

/HighPitch

**Comment by JoshuaEN** [comment]
For the first issue (showing 0 battles), from the point of view of a player I can see why that would be useless, however this page is, at least partly, targeted at recruiters, and showing tanks which a player most certainly has the XP for--but hasn't bought (or played a game in)--is useful for determining how close that player is to getting the tier 10. I would be open to displaying something other than 0 battles remaining, or perhaps changing how such information is displayed, however I still think having the information displayed somewhere is useful.

As to the second issue, this is an unfortunate problem caused by the gaps in what is accessible via WG's API and isn't something I can fix. WG makes available a list of the player's tanks, but only tanks they have played at least one battle in. No information is available for tanks which have been researched but not yet bought, or without at least one game played. Furthermore, the only per-a-player data available with regards to progression (unlocked modules) is the overall XP earned on the tank, which severely limits how accurate the estimated XP progress can be.

Thank you for your report,
Unknown0ne

**Comment by highpitch** [comment]
Ok, just as long as it's working as intended, and not something that needs to be addressed.
