### ISSUE TITLE
Battles in multiple days

### ISSUE THREAD

**Issue by BONNe** [ClanTools/Tracker#13]
Hello,
There are a problem with landing battles spliting in two days, if the battle was after 01:00.

![screen1](https://cloud.githubusercontent.com/assets/1344358/11556544/17066c2c-99b0-11e5-86bc-baf2115302c0.PNG)
![screen2](https://cloud.githubusercontent.com/assets/1344358/11556545/1708d692-99b0-11e5-926f-842bcce12018.PNG)

**Comment by JoshuaEN** [comment]
Thank you for your report.

Each server region is assigned a timezone internally in Clan Tools which, among other things, determines which day a battle is considered for. I either made a miscalculation when I selected EU's timezone or the latest timezone for EU changed; either way Berlin time doesn't work for this.

Changing this time zone requires updating some user-set values, so I'll need to look into how best to approach this problem, but I do have an idea and hope to have this fixed by tomorrow.

Sorry for the inconvenience.

**Comment by JoshuaEN** [comment]
This should now be fixed, changelog: http://blog.clantools.us/2015/12/changelog-for-2015-12-05.html

Apologies for the delay, an inconstancy came up in testing and I needed to confirm it was benign.
