### ISSUE TITLE
no battles showing

### ISSUE THREAD

**Issue by FloggHARM** [ClanTools/Tracker#30]
can not upload battles not showing any  for today

**Comment by FloggHARM** [comment]
![untitled](https://user-images.githubusercontent.com/41554723/43052026-a6dadd5e-8df7-11e8-9b74-b844de0dbf67.png)

**Comment by JoshuaEN** [comment]
Hi,

The background task service that loads battles crashed, which caused this issue. I've restarted the service and new battles should appear shortly if they haven't already.

Unfortunately, because WG does not retain historic battle data, any battles that finished before the service was restarted will not be loaded. If you want to still upload replays for those missing battles, you could use the Matches system (which is the generic version of the Battle uploading system).

Sorry for the inconvenience.
